<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="40" started-at="2016-05-04T06:39:38Z" finished-at="2016-05-04T06:39:39Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="40" started-at="2016-05-04T06:39:38Z" finished-at="2016-05-04T06:39:39Z">
      <class name="com.creditease.xyuan.httpTest.test.testngRun2">
        <test-method status="FAIL" signature="aaaa()[pri:0, instance:com.creditease.xyuan.httpTest.test.testngRun2@369bb]" name="aaaa" duration-ms="10" started-at="2016-05-04T14:39:39Z" finished-at="2016-05-04T14:39:39Z">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[sdf]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: sdf
	at com.creditease.xyuan.httpTest.test.testngRun2.aaaa(testngRun2.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aaaa -->
        <test-method status="PASS" signature="runTestCase(int)[pri:0, instance:com.creditease.xyuan.httpTest.test.testngRun2@369bb]" name="runTestCase" duration-ms="0" started-at="2016-05-04T14:39:39Z" data-provider="test" finished-at="2016-05-04T14:39:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runTestCase -->
        <test-method status="PASS" signature="runTestCase(int)[pri:0, instance:com.creditease.xyuan.httpTest.test.testngRun2@369bb]" name="runTestCase" duration-ms="10" started-at="2016-05-04T14:39:39Z" data-provider="test" finished-at="2016-05-04T14:39:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runTestCase -->
      </class> <!-- com.creditease.xyuan.httpTest.test.testngRun2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
